/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include </usr/lib/jvm/java-8-openjdk-amd64/include/jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


    #include <pcap.h>
    #include <errno.h> 
    #include <sys/socket.h> 
    #include <netinet/in.h> 
    #include <arpa/inet.h> 
    #include <netinet/if_ether.h> /* includes net/ethernet.h */ 
    #include <netinet/ether.h>
    #include <string.h>
    #include <time.h>
      typedef struct
  {
        int capacity;
        int size;
        int front;
        int rear;
        char **elements;
  } Queue;
    extern char *dev;  
    extern pcap_t* descr; 
    extern char *filter;


    extern Queue * createQueue(int maxElements);
    extern void Dequeue(Queue *Q);
    extern char* front(Queue *Q);
    extern void Enqueue(Queue *Q,char *element);


    extern void handleDev(char * netif);
    extern void handleDescr();
    extern void capture(Queue * q);
    extern void stop(pcap_t *descr);
    extern void capture1(Queue * q);



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Queue_1capacity_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Queue *arg1 = (Queue *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->capacity = arg2;
}


SWIGEXPORT jint JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Queue_1capacity_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Queue *arg1 = (Queue *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  result = (int) ((arg1)->capacity);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Queue_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Queue *arg1 = (Queue *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jint JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Queue_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Queue *arg1 = (Queue *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  result = (int) ((arg1)->size);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Queue_1front_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Queue *arg1 = (Queue *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->front = arg2;
}


SWIGEXPORT jint JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Queue_1front_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Queue *arg1 = (Queue *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  result = (int) ((arg1)->front);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Queue_1rear_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  Queue *arg1 = (Queue *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->rear = arg2;
}


SWIGEXPORT jint JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Queue_1rear_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  Queue *arg1 = (Queue *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  result = (int) ((arg1)->rear);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Queue_1elements_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Queue *arg1 = (Queue *) 0 ;
  char **arg2 = (char **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  arg2 = *(char ***)&jarg2; 
  if (arg1) (arg1)->elements = arg2;
}


SWIGEXPORT jlong JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Queue_1elements_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Queue *arg1 = (Queue *) 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  result = (char **) ((arg1)->elements);
  *(char ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_new_1Queue(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Queue *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Queue *)calloc(1, sizeof(Queue));
  *(Queue **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_delete_1Queue(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Queue *arg1 = (Queue *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Queue **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_dev_1set(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  {
    free(dev);
    if (arg1) {
      dev = (char *) malloc(strlen((const char *)arg1)+1);
      strcpy((char *)dev, (const char *)arg1);
    } else {
      dev = 0;
    }
  }
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jstring JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_dev_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)dev;
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_descr_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  pcap_t *arg1 = (pcap_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(pcap_t **)&jarg1; 
  descr = arg1;
}


SWIGEXPORT jlong JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_descr_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  pcap_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (pcap_t *)descr;
  *(pcap_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_filter_1set(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  {
    free(filter);
    if (arg1) {
      filter = (char *) malloc(strlen((const char *)arg1)+1);
      strcpy((char *)filter, (const char *)arg1);
    } else {
      filter = 0;
    }
  }
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jstring JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_filter_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)filter;
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_createQueue(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  Queue *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (Queue *)createQueue(arg1);
  *(Queue **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Dequeue(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Queue *arg1 = (Queue *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  Dequeue(arg1);
}


SWIGEXPORT jstring JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_front(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  Queue *arg1 = (Queue *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  result = (char *)front(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_Enqueue(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  Queue *arg1 = (Queue *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  Enqueue(arg1,arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_handleDev(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  handleDev(arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_handleDescr(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  handleDescr();
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_capture(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Queue *arg1 = (Queue *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  capture(arg1);
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_stop(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  pcap_t *arg1 = (pcap_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(pcap_t **)&jarg1; 
  stop(arg1);
}


SWIGEXPORT void JNICALL Java_eu_arrowhead_client_consumer_lpcap_testeJNI_capture1(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  Queue *arg1 = (Queue *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Queue **)&jarg1; 
  capture1(arg1);
}


#ifdef __cplusplus
}
#endif

